### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by Youlenda**

### CODE REVIEW

**Comment by Youlenda** [comment]
_config.yml

**Comment by Youlenda** [comment]
profile

**Comment by Youlenda** [comment]
c

**Comment by Youlenda** [comment]
c

**Comment by Youlenda** [comment]
c

**Comment by Youlenda** [comment]
c

**Review by DavidLee528 — CHANGES_REQUESTED** [review]
Those commits seems contain the author's personal information and should not merge into this repository.

**Comment by DavidLee528** [comment]
Dear @Youlenda , commit in your own fork in enough for updating your homepage, no need to open any pull request unless you have any modification of general stuffs for the repository you fork from. 

Any problems, please contact.

**Comment by Youlenda** [comment]
1

**Pull request closed without merging**
