### PR TITLE
gitlab support added in author profile

### PR DESCRIPTION
**Pull request by thiagogomesverissimo**

### CODE REVIEW

**Comment by c-martinez** [comment]
This looks like a good improvement. Is there a reason why this PR never got merged?

**Comment by rjzupkoii** [comment]
@c-martinez Most likely because it was closed by the OP when the project was in a dormant state.

**Comment by thiagogomesverissimo** [comment]
If the maintainer prefers, I can resubmit the pull request.

**Comment by rjzupkoii** [comment]
@thiagogomesverissimo A resubmission might be best, the `_config.yml` and `author-profile.html` files have changed a bit, so I'd have to see what the merge looks like, but it's a fairly simple change so it should get accepted right away.

**Pull request closed without merging**
